[package]
name = "tor_cell_codec"
version = "0.1.0"
edition = "2021"

[lib]
name = "tor_cell_codec"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
tor-cell = "0.25"
bytes = "1.0"